### ISSUE TITLE
__str__

### ISSUE THREAD

**Issue by ArtemKonshyn** [Vadim-Ryabichenko/a-level-vadim#10]
https://github.com/Vadim-Ryabichenko/a-level-vadim/blob/145ea5636afadfccc9a703aff86e0b9357d3d0a5/OOP/tests/test_Candidate.py#L23C9-L23C31

Напряму магічні методи не викликаємо!

**Comment by shorodilov** [comment]
https://github.com/Vadim-Ryabichenko/a-level-vadim/blob/145ea5636afadfccc9a703aff86e0b9357d3d0a5/OOP/tests/test_Candidate.py#L23C9-L23C31

```suggestion
self.assertEqual(repr(Candidate.generate_candidates(path)), str(expected_candidates))
```
