### ISSUE TITLE
with open("/home/vadim/a_level_vadim/OOP/emails.csv", "a") as file:

### ISSUE THREAD

**Issue by ArtemKonshyn** [Vadim-Ryabichenko/a-level-vadim#6]
https://github.com/Vadim-Ryabichenko/a-level-vadim/blob/d4b635405fac915dc62d89101b09a5de512fb47a/OOP/17_Employee.py#L36C9-L36C76

просто with open("emails.csv", "a") as file:

не треба повний шлях прописувати
на кожному компʼютері він буде різний

**Comment by shorodilov** [comment]
https://github.com/Vadim-Ryabichenko/a-level-vadim/blame/de4176dee372c81b7075d01af603f5aa18c88da2/OOP/employee17.py#L6

Те, що ти прибрав абсолютний шлях до змінної не виправляє зазначенної помилки.
Користуйся або відносними шляхами, або бібліотекою `pathlib`.
Не використовуй шляхи, визначені для конкретної системи як константи.

**Comment by Vadim-Ryabichenko** [comment]
Наче розібрався, просто не з тої директорії запускав програму і не бачило моїх файлів, тому і писав повний шлях
