### ISSUE TITLE
__repr__

### ISSUE THREAD

**Issue by ArtemKonshyn** [Vadim-Ryabichenko/a-level-vadim#8]
https://github.com/Vadim-Ryabichenko/a-level-vadim/blob/d4b635405fac915dc62d89101b09a5de512fb47a/OOP/18_Employee.py#L86

це дублікат str
можна тоді просто 
return self.__str__()

**Comment by shorodilov** [comment]
Воно не виправлене: https://github.com/Vadim-Ryabichenko/a-level-vadim/blob/de4176dee372c81b7075d01af603f5aa18c88da2/OOP/employee18.py#L94C1-L99C1
